DROP TABLE article;

CREATE TABLE article (
    id SERIAL PRIMARY KEY,
    titre VARCHAR(100),
    contenu TEXT,
    image VARCHAR(255),
    url VARCHAR(255),
    dateheure TIMESTAMP,
    type CHAR(2)
);


-- causes
INSERT INTO article VALUES
(DEFAULT, 'Production d’énergie', 'Une grande partie des émissions mondiales de gaz à effet de serre provient de l’utilisation de combustibles fossiles — tels que le charbon, le pétrole et le gaz naturel — pour produire de l’électricité et de la chaleur. La production d’électricité dépend encore majoritairement des combustibles fossiles. Seul un quart de notre électricité provient de sources éoliennes, solaires et d’autres sources renouvelables.', 'production-denergie.jpg', 'causes/production-denergie', NOW(), 'ca'),
(DEFAULT, 'Production industrielle', 'La production industrielle rejette des émissions de gaz, essentiellement du fait de son utilisation des combustibles fossiles pour produire l’énergie nécessaire à la fabrication de matériaux tels que le ciment, le fer, l’acier, l’électronique, le plastique et le textile, ainsi que d’autres biens. L’exploitation minière et d’autres processus industriels produisent également des émissions.', 'production-industrielle.jpg', 'causes/production-industrielle', NOW(), 'ca'),
(DEFAULT, 'Déforestation', 'La déforestation au profit d’exploitations agricoles, de pâturages ou autre, rejette également des émissions de gaz à effet de serre, puisque les arbres, lorsqu’ils sont abattus, libèrent le carbone qu’ils ont stocké. La destruction des forêts, qui absorbent le dioxyde de carbone, limite également la capacité de la nature à empêcher les émissions de gaz d’entrer dans l’atmosphère.', 'deforestation.jpg', 'causes/deforestation', NOW(), 'ca'),
(DEFAULT, 'Utilisation des transports', 'La plupart des voitures, camions, bateaux et avions fonctionnent aux combustibles fossiles. Par conséquent, les transports contribuent largement à la production de gaz à effet de serre, en particulier les émissions de dioxyde de carbone. Les véhicules routiers sont responsables de la majeure partie de ces émissions, mais celles des navires et des avions ne cessent de croître.', 'utilisation-des-transports.jpg', 'causes/utilisation-des-transports', NOW(), 'ca'),
(DEFAULT, 'Production alimentaire', 'La production alimentaire a besoin d’énergie pour faire fonctionner les équipements agricoles ou les bateaux de pêche, qui utilisent généralement des combustibles fossiles. Les cultures ont également un impact sur les émissions de gaz, notamment parce qu’elles nécessitent l’utilisation d’engrais et de fumier. Le bétail produit du méthane, un puissant gaz à effet de serre. Enfin, le conditionnement et la distribution des aliments génèrent aussi des émissions de gaz.', 'production-alimentaire.jpg', 'causes/production-alimentaire', NOW(), 'ca'),
(DEFAULT, 'Alimentation des bâtiments', 'À l’échelle mondiale, les bâtiments résidentiels et commerciaux consomment plus de la moitié de l’électricité produite. Ils continuent à dépendre du charbon, du pétrole et du gaz naturel pour le chauffage et la climatisation, et émettent donc d’importantes quantités de gaz à effet de serre. Pour en savoir plus sur l’impact de l’ali', 'alimentation-des-batiments.jpg', 'causes/alimentation-des-batiments', NOW(), 'ca'),
(DEFAULT, 'Surconsommation', 'Notre maison, notre consommation d’énergie, nos déplacements, notre alimentation et la quantité de déchets que nous jetons contribuent tous aux émissions de gaz à effet de serre. Il en va de même pour la consommation de biens, tels que les vêtements, les appareils électroniques et les matières plastiques.', 'surconsommation.jpg', 'causes/surconsommation', NOW(), 'ca');

-- conséquences
INSERT INTO article VALUES
(DEFAULT, 'Hausse des températures', 'Dans la quasi-totalité des régions terrestres, les journées très chaudes et les vagues de chaleur se multiplient. L’année 2020 a été l’une des plus chaudes jamais enregistrées. La hausse des températures provoque une augmentation des maladies liées à la chaleur et peut rendre le travail et les déplacements plus difficiles. En outre, les incendies de forêt démarrent plus facilement et se propagent plus vite lorsque les températures sont plus élevées.', 'hausse-des-temperatures.jpeg', 'consequences/hausse-des-temperatures', NOW(), 'co'),
(DEFAULT, 'Accroissement de la gravité des tempêtes', 'Les changements de température occasionnent à leur tour des changements dans les précipitations. Cela se traduit par des tempêtes plus violentes et plus fréquentes, susceptibles de provoquer des inondations et des glissements de terrain, de détruire des maisons et des communautés, et de coûter des milliards de dollars.', 'accroissement-de-la-gravite-des-tempetes.jpg', 'consequences/accroissement-de-la-gravite-des-tempetes', NOW(), 'co'),
(DEFAULT, 'Accroissement des sécheresses', 'De plus en plus de régions sont confrontées à une pénurie d’eau. Les sécheresses peuvent provoquer des tempêtes de sable et de poussière destructrices, capables de déplacer des milliards de tonnes de sable à travers les continents. Avec la désertification, les terres cultivables voient également leur surface se réduire. Aujourd’hui, de nombreuses personnes sont exposées au risque de manquer d’eau.', 'accroissement-des-secheresses.jpg', 'consequences/accroissement-des-secheresses', NOW(), 'co'),
(DEFAULT, 'Réchauffement et montée des océans', 'Les océans absorbent une grande partie de la chaleur due au réchauffement de la planète. Cela a pour effet de provoquer la fonte des calottes glaciaires et l’élévation du niveau des mers, menaçant ainsi les communautés côtières et insulaires. Les océans absorbent également le dioxyde de carbone contenu dans l’atmosphère. Or, l’augmentation du dioxyde de carbone rend l’océan plus acide, ce qui met en danger la vie marine.', 'rechauffement-et-montee-des-oceans.jpg', 'consequences/rechauffement-et-montee-des-oceans', NOW(), 'co'),
(DEFAULT, 'Perte de biodiversité', 'Les changements climatiques menacent la survie des espèces sur terre et dans les océans. Plus les températures sont élevées, plus les risques encourus augmentent. Les incendies de forêt, les conditions météorologiques extrêmes, les espèces nuisibles et les maladies comptent parmi les nombreuses menaces liées aux changements climatiques. Si certaines espèces sont en mesure de se déplacer et de survivre, d’autres ne peuvent pas en faire autant.', 'perte-de-biodiversite.jpg', 'consequences/perte-de-biodiversite', NOW(), 'co'),
(DEFAULT, 'Pénurie alimentaire', 'La progression de la faim et de la malnutrition dans le monde s’explique notamment par les changements climatiques et l’augmentation des phénomènes météorologiques extrêmes. Les ressources halieutiques, les cultures et le bétail sont exposés au risque de destruction ou de perte de productivité. En outre, le stress thermique peut entraîner une diminution des ressources en eau et des prairies pour le pâturage.', 'penurie-alimentaire.jpg', 'consequences/penurie-alimentaire', NOW(), 'co'),
(DEFAULT, 'Augmentation des risques pour la santé', 'L’évolution des conditions météorologiques favorise la propagation de maladies telles que le paludisme. Les phénomènes météorologiques extrêmes entraînent une augmentation des maladies et des décès et mettent à mal les systèmes de santé. Parmi les autres risques pour la santé figure également l’augmentation de la famine et de la malnutrition dans des régions où il est impossible de cultiver ou de trouver suffisamment de nourriture.', 'augmentation-des-risques-pour-la-sante.jpg', 'consequences/augmentation-des-risques-pour-la-sante', NOW(), 'co'),
(DEFAULT, 'Pauvreté et déplacement', 'Les changements climatiques accentuent les facteurs qui contribuent à la pauvreté. Par exemple, les inondations peuvent balayer les bidonvilles et détruire les maisons et les moyens de subsistance ; la chaleur peut rendre difficile le travail en extérieur. Chaque année, les catastrophes liées aux conditions météorologiques entraînent le déplacement de 23 millions de personnes et les rendent encore plus vulnérables à la pauvreté.', 'pauvrete-et-deplacement.jpg', 'consequences/pauvrete-et-deplacement', NOW(), 'co');

-- solutions
INSERT INTO article VALUES
(DEFAULT, 'Économiser l’énergie à la maison', 'Notre électricité et notre chauffage proviennent en grande partie du charbon, du pétrole et du gaz. Il est possible de réduire sa consommation d’énergie en diminuant le chauffage et la climatisation, en optant pour des ampoules LED et des appareils électriques à faible consommation, en lavant son linge à l’eau froide ou en le suspendant pour le faire sécher au lieu d’utiliser un sèche-linge.', 'economiser-lenergie-a-la-maison.jpg', 'solutions/economiser-lenergie-a-la-maison', NOW(), 'so'),
(DEFAULT, 'Se déplacer à pied, à vélo ou en transports en commun', 'Partout dans le monde, les routes sont surchargées de véhicules, dont la plupart roulent au diesel ou à l’essence. Privilégier la marche ou le vélo à la voiture permet de réduire les émissions de gaz à effet de serre et contribue à une meilleure santé et à une meilleure forme physique. Pour les longues distances, pensez à prendre le train ou le car. Enfin, pratiquez le covoiturage chaque fois que cela est possible.', 'se-deplacer-a-pied-a-velo-ou-en-transports-en-commun.jpg', 'solutions/se-deplacer-a-pied-a-velo-ou-en-transports-en-commun', NOW(), 'so'),
(DEFAULT, 'Consommer plus d’aliments d’origine végétale', 'En consommant plus de légumes, de fruits, de céréales complètes, de légumineuses, de noix et de graines, et moins de viande et de produits laitiers, on peut réduire considérablement son impact sur l’environnement. La production d’aliments d’origine végétale entraîne généralement moins d’émissions de gaz à effet de serre et nécessite moins d’énergie, de terres et d’eau.', 'consommer-plus-daliments-dorigine-vegetale.jpg', 'solutions/consommer-plus-daliments-dorigine-vegetale', NOW(), 'so'),
(DEFAULT, 'Réfléchir à ses déplacements', 'Les avions consomment de grandes quantités de combustibles fossiles et produisent d’importantes émissions de gaz à effet de serre. Par conséquent, prendre moins souvent l’avion constitue l’un des moyens les plus efficaces de réduire son impact sur l’environnement. Dans la mesure du possible, organisez des réunions virtuelles, prenez le train ou évitez tout simplement les voyages longue distance.', 'reflechir-a-ses-deplacements.jpg', 'solutions/reflechir-a-ses-deplacements', NOW(), 'so'),
(DEFAULT, 'Éviter le gaspillage alimentaire', 'Lorsque l’on jette de la nourriture, on gaspille également les ressources et l’énergie qui ont été utilisées pour la cultiver, la produire, l’emballer et la transporter. Par ailleurs, une fois dans un site d’enfouissement des déchets, les aliments se décomposent et produisent du méthane, un puissant gaz à effet de serre. Veillez donc à consommer les aliments que vous achetez et à composter vos déchets.', 'eviter-le-gaspillage-alimentaire.jpg', 'solutions/eviter-le-gaspillage-alimentaire', NOW(), 'so'),
(DEFAULT, 'Réduire, réutiliser, réparer et recycler', 'Les appareils électroniques, les vêtements et tous les autres biens que nous achetons génèrent des émissions de carbone à chaque étape de leur production, de l’extraction des matières premières à la fabrication et au transport des marchandises jusqu’au lieu de vente. Pour protéger notre climat, achetez moins, choisissez des articles d’occasion, réparez tout ce que vous pouvez et recyclez.', 'reduire-reutiliser-reparer-et-recycler.jpg', 'solutions/reduire-reutiliser-reparer-et-recycler', NOW(), 'so'),
(DEFAULT, 'Opter pour une source d’énergie alternative à la maison', 'Demandez à votre compagnie d’électricité si l’énergie que vous utilisez chez vous provient du pétrole, du charbon ou du gaz. Si possible, essayez de passer à des sources renouvelables comme l’énergie éolienne ou solaire. Mieux encore : installez des panneaux solaires sur votre toit pour produire de l’énergie à usage domestique.', 'opter-pour-une-source-denergie-alternative-a-la-maison.jpg', 'solutions/opter-pour-une-source-denergie-alternative-a-la-maison', NOW(), 'so'),
(DEFAULT, 'Passer à un véhicule électrique', 'En cas d’achat d’une nouvelle voiture, envisagez d’opter pour un modèle électrique. Ces modèles sont de plus en plus nombreux et de moins en moins chers sur le marché. Même si elles fonctionnent toujours grâce à de l’électricité produite à partir de combustibles fossiles, les voitures électriques contribuent à réduire la pollution atmosphérique et libèrent beaucoup moins d’émissions de gaz à effet de serre que les véhicules à moteur essence ou diesel.', 'passer-a-un-vehicule-electrique.jpg', 'solutions/passer-a-un-vehicule-electrique', NOW(), 'so');